trigger: none

extends:
    template: ../../eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      ServiceDirectory: servicebus
      TestTimeoutInMinutes: 960
      BuildTargetingString: azure-servicebus*
      EnvVars:
        AZURE_SUBSCRIPTION_ID: $(SERVICEBUS_SUBSCRIPTION_ID)
        AZURE_TEST_RUN_LIVE: 'true'
        AZURE_SKIP_LIVE_RECORDING: 'True'
      MatrixFilters:
        - PythonVersion=^(?!pypy3).*
      Clouds: 'Public,Canary'
      SupportedClouds: 'Public,UsGov,China'
      CloudConfig:
        Public:
        Canary:
          ServiceConnection: azure-sdk-tests-public
          Location: 'eastus2euap'
        UsGov:
          ServiceConnection: usgov_azure-sdk-tests
          Location: 'usgovarizona'
