trigger: none

parameters:
  - name: Services
    type: object
    default:
      - azure-keyvault-secrets
      - azure-keyvault-certificates

extends:
    template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      ServiceDirectory: keyvault
      Packages: ${{ parameters.Services }}
      SupportedClouds: 'Public,UsGov,China'
      TestTimeoutInMinutes: 240
      CloudConfig:
        Public:
        UsGov:
          ServiceConnection: usgov_azure-sdk-tests
          MatrixFilters:
            - ArmTemplateParameters=^(?!.*enableHsm.*true)
        China:
          ServiceConnection: china_azure-sdk-tests 
          MatrixFilters:
            - ArmTemplateParameters=^(?!.*enableHsm.*true)
          Location: chinaeast2
      EnvVars:
        AZURE_TEST_RUN_LIVE: true
        AZURE_SKIP_LIVE_RECORDING: 'True'
        AZURE_SUBSCRIPTION_ID: $(azure-subscription-id)
        AZURE_CLIENT_OID: $(aad-azure-sdk-test-client-oid)
