trigger: none

extends:
    template: ../../eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      BuildTargetingString: azure-containerregistry
      ServiceDirectory: containerregistry
      SupportedClouds: 'Public,UsGov,China'
      TestTimeoutInMinutes: 240
      CloudConfig:
        Public:
        UsGov:
          ServiceConnection: usgov_azure-sdk-tests
        China:
          ServiceConnection: china_azure-sdk-tests
          Location: chinanorth3
      MatrixReplace:
        - TestSamples=.*/true
      EnvVars:
        TEST_MODE: 'RunLiveNoRecord'
        AZURE_TEST_RUN_LIVE: 'true'
        AZURE_SKIP_LIVE_RECORDING: 'True'
